// import { activity } from "./activity/activity.module";
// import { charts } from "./charts/charts.module";
// import { exposure } from "./exposure/exposure.module";
// import { highlighter } from "./highlighter/highlighter.module";
// import { news } from "./news/news.module";
// import { ohlcChart } from "./ohlc-chart/ohlc-chart.module";
// import { orderDialog } from "./order-dialog/order-dialog.module";
// import { plugins } from "./plugins/plugins.module";
// import { settingsDialog } from "./settings-dialog/settings-dialog.module";
// import { slChart } from "./sl-chart/sl-chart.module";
// import { yesnoDialog } from "./yesno-dialog/yesno-dialog.module";

import "./account/account.module";
import "./header/header.module";
import "./orders/orders.module";
import "./positions/positions.module";
import "./quotes/quotes.module";
import "./session/session.module";
import "./streaming/streaming.module";
import "./toasts/toasts.module";
import "./token-dialog/token-dialog.module";
import "./trades/trades.module";
